import { loadData, saveData, downloadJson, downloadCsv } from './storage.js';
import { uid, today, currentMonth, formatMoney, monthName, toMinor, esc, selectedMonthItems } from './utils.js';

let data = loadData();
let view = 'dashboard', month = currentMonth();
const $ = s => document.querySelector(s);
const titles = { dashboard:['Обзор','Добрый день!'], transactions:['Операции','Все операции'], budgets:['Планирование','Бюджет'], goals:['Накопления','Цели'], statistics:['Аналитика','Статистика'], settings:['Данные','Настройки'] };
const money = n => formatMoney(n, data.currency);
const monthTransactions = () => selectedMonthItems(data.transactions, month);
const expenses = items => items.filter(x => x.type === 'expense').reduce((s,x) => s + x.amount, 0);
const incomes = items => items.filter(x => x.type === 'income').reduce((s,x) => s + x.amount, 0);
const persist = () => { saveData(data); render(); };

function render() {
  document.documentElement.dataset.theme = data.theme;
  $('#theme-toggle').innerHTML = data.theme === 'dark' ? '☀ <span>Светлая тема</span>' : '◐ <span>Тёмная тема</span>';
  const [kicker, title] = titles[view]; $('#page-kicker').textContent = kicker; $('#page-title').textContent = title;
  $('#month-picker').value = month;
  document.querySelectorAll('.page').forEach(x => x.classList.toggle('active', x.id === `${view}-page`));
  document.querySelectorAll('.nav-link').forEach(x => x.classList.toggle('active', x.dataset.page === view));
  dashboard(); transactions(); budgets(); goals(); statistics(); settings();
}

function cardsHtml() {
  const allBalance = incomes(data.transactions) - expenses(data.transactions), items = monthTransactions();
  const inc = incomes(items), exp = expenses(items);
  const days = new Date(+month.slice(0,4), +month.slice(5,7), 0).getDate();
  const left = Math.max(1, days - (new Date().getMonth() + 1 === +month.slice(5,7) ? new Date().getDate() : 0));
  return `<div class="summary-grid"><article class="summary-card balance"><span>Общий остаток</span><strong>${money(allBalance)}</strong><small>Все операции</small></article><article class="summary-card income"><span>Доходы за месяц</span><strong>${money(inc)}</strong><small>Поступления в ${monthName(month)}</small></article><article class="summary-card expense"><span>Расходы за месяц</span><strong>${money(exp)}</strong><small>Траты в ${monthName(month)}</small></article><article class="summary-card"><span>До конца месяца</span><strong>${money(Math.max(0, inc - exp))}</strong><small>${left} дн. в запасе</small></article></div>`;
}
function txRow(x, actions = true) { return `<li class="transaction"><span class="tx-icon ${x.type}">${x.type === 'income' ? '↗' : '↘'}</span><div class="tx-info"><b>${esc(x.category)}</b><small>${new Date(x.date + 'T12:00').toLocaleDateString('ru-RU')} · ${esc(x.payment)}${x.note ? ' · ' + esc(x.note) : ''}</small></div><strong class="${x.type}">${x.type === 'income' ? '+' : '−'}${money(x.amount)}</strong>${actions ? `<button class="icon-btn" data-action="edit-tx" data-id="${x.id}" aria-label="Редактировать">⋮</button>` : ''}</li>`; }
function empty(text) { return `<div class="empty">${text}</div>`; }

function dashboard() {
  const recent = [...data.transactions].sort((a,b) => b.date.localeCompare(a.date)).slice(0,5);
  const due = data.reminders.filter(x => !x.paid).sort((a,b) => a.date.localeCompare(b.date)).slice(0,4);
  $('#dashboard-page').innerHTML = `${cardsHtml()}<div class="section-grid"><section class="panel"><div class="panel-head"><h2>Последние операции</h2><button class="link-btn" data-go="transactions">Все операции</button></div><ul class="transaction-list">${recent.length ? recent.map(x => txRow(x, false)).join('') : empty('Добавьте первую операцию — баланс появится здесь.')}</ul></section><section class="panel"><div class="panel-head"><h2>Ближайшие платежи</h2><button class="link-btn" data-action="add-reminder">+ Добавить</button></div><ul class="reminder-list">${due.length ? due.map(x => `<li><span class="reminder-date">${new Date(x.date+'T12:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</span><div><b>${esc(x.name)}</b><small>${x.amount ? money(x.amount) : 'Сумма не указана'} · ${esc(x.category)}</small></div><button class="check-btn" title="Отметить оплаченным" data-action="pay-reminder" data-id="${x.id}">✓</button></li>`).join('') : empty('Нет ближайших напоминаний.')}</ul></section></div>`;
}

function transactions() {
  const cats = [...data.categories.expense, ...data.categories.income];
  const rows = [...monthTransactions()].sort((a,b) => b.date.localeCompare(a.date));
  $('#transactions-page').innerHTML = `<section class="toolbar"><label>Месяц <input type="month" id="tx-month" value="${month}"></label><label>Тип <select id="tx-type"><option value="">Все</option><option value="expense">Расходы</option><option value="income">Доходы</option></select></label><label>Категория <select id="tx-category"><option value="">Все категории</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><button class="primary" data-action="add-tx">+ Операция</button></section><section class="panel"><ul class="transaction-list" id="all-transactions">${rows.length ? rows.map(txRow).join('') : empty('В этом месяце операций пока нет.')}</ul></section>`;
}

function budgets() {
  const spent = monthTransactions();
  $('#budgets-page').innerHTML = `<div class="page-intro"><p>Установите лимит на месяц для нужных категорий. Прогресс пересчитывается автоматически.</p><button class="primary" data-action="add-budget">+ Лимит</button></div><section class="budget-grid">${data.budgets.length ? data.budgets.map(b => { const used = expenses(spent.filter(x => x.category === b.category)); const pc = b.limit ? Math.round(used/b.limit*100) : 0; return `<article class="panel budget-card"><div class="panel-head"><div><h2>${esc(b.category)}</h2><small>${money(used)} из ${money(b.limit)}</small></div><button class="icon-btn" data-action="delete-budget" data-id="${b.id}">×</button></div><div class="progress"><i class="${pc > 100 ? 'over' : pc > 80 ? 'warning' : ''}" style="width:${Math.min(pc,100)}%"></i></div><div class="budget-foot"><span>${pc > 100 ? 'Превышен на ' + money(used-b.limit) : 'Осталось ' + money(b.limit-used)}</span><b>${pc}%</b></div></article>`; }).join('') : empty('Лимиты ещё не заданы.')}</section>`;
}

function goals() {
  $('#goals-page').innerHTML = `<div class="page-intro"><p>Копите на важное и наблюдайте за прогрессом.</p><button class="primary" data-action="add-goal">+ Новая цель</button></div><section class="goal-grid">${data.goals.length ? data.goals.map(g => { const pc = Math.min(100, Math.round(g.current/g.target*100)); return `<article class="panel goal-card"><div class="goal-title"><span style="background:${esc(g.color)}">${esc(g.icon || '◎')}</span><div><h2>${esc(g.name)}</h2><small>${g.deadline ? 'До ' + new Date(g.deadline+'T12:00').toLocaleDateString('ru-RU') : 'Без срока'}</small></div><button class="icon-btn" data-action="delete-goal" data-id="${g.id}">×</button></div><strong>${money(g.current)} <small>из ${money(g.target)}</small></strong><div class="progress"><i style="width:${pc}%;background:${esc(g.color)}"></i></div><div class="goal-foot"><span>${pc}% · осталось ${money(Math.max(0,g.target-g.current))}</span><button class="small-btn" data-action="fund-goal" data-id="${g.id}">Пополнить</button></div></article>` }).join('') : empty('Создайте цель, чтобы начать копить.')}</section>`;
}

function statistics() {
  const list = monthTransactions(), exp = expenses(list), inc = incomes(list);
  const grouped = Object.entries(list.filter(x=>x.type==='expense').reduce((a,x)=>(a[x.category]=(a[x.category]||0)+x.amount,a),{})).sort((a,b)=>b[1]-a[1]);
  $('#statistics-page').innerHTML = `${cardsHtml()}<div class="section-grid"><section class="panel"><div class="panel-head"><h2>Расходы по категориям</h2><span>${money(exp)}</span></div><div class="category-bars">${grouped.length ? grouped.map(([name,value]) => `<div><div><span>${esc(name)}</span><b>${money(value)} · ${Math.round(value/exp*100)}%</b></div><i><em style="width:${value/exp*100}%"></em></i></div>`).join('') : empty('Добавьте расходы, чтобы увидеть статистику.')}</div></section><section class="panel"><h2>Сводка за месяц</h2><dl class="stats"><div><dt>Доходы</dt><dd class="income">${money(inc)}</dd></div><div><dt>Расходы</dt><dd class="expense">${money(exp)}</dd></div><div><dt>Баланс месяца</dt><dd>${money(inc-exp)}</dd></div><div><dt>Крупнейшая трата</dt><dd>${list.filter(x=>x.type==='expense').sort((a,b)=>b.amount-a.amount)[0] ? money(list.filter(x=>x.type==='expense').sort((a,b)=>b.amount-a.amount)[0].amount) : '—'}</dd></div></dl><button class="secondary full" data-action="export-csv">Экспорт операций CSV</button></section></div>`;
}

function settings() {
  const cat = type => data.categories[type].map((x,i)=>`<li><span>${esc(x)}</span><button class="icon-btn" data-action="remove-category" data-type="${type}" data-index="${i}" aria-label="Удалить">×</button></li>`).join('');
  $('#settings-page').innerHTML = `<div class="settings-grid"><section class="panel"><h2>Основные</h2><label class="field">Валюта<select id="currency"><option value="KZT" ${data.currency==='KZT'?'selected':''}>Тенге (₸)</option><option value="RUB" ${data.currency==='RUB'?'selected':''}>Рубль (₽)</option><option value="USD" ${data.currency==='USD'?'selected':''}>Доллар ($)</option><option value="EUR" ${data.currency==='EUR'?'selected':''}>Евро (€)</option></select></label></section><section class="panel"><h2>Категории</h2><h3>Расходы</h3><ul class="plain-list">${cat('expense')}</ul><button class="secondary" data-action="add-category" data-type="expense">+ Категория расхода</button><h3>Доходы</h3><ul class="plain-list">${cat('income')}</ul><button class="secondary" data-action="add-category" data-type="income">+ Категория дохода</button></section><section class="panel"><h2>Резервная копия</h2><p>Все данные хранятся только в этом браузере. Сохраните копию перед переносом на другое устройство.</p><div class="button-stack"><button class="primary" data-action="export-json">Скачать JSON</button><button class="secondary" data-action="import-json">Импортировать JSON</button></div></section><section class="panel danger-zone"><h2>Удаление данных</h2><p>Это действие необратимо. Рекомендуем сначала экспортировать резервную копию.</p><button class="danger" data-action="clear-data">Удалить все данные</button></section></div>`;
}

function openModal(title, html, submit = null) { $('#modal-content').innerHTML = `<h2>${title}</h2>${html}`; $('#modal').showModal(); $('#modal-form').onsubmit = e => { if (e.submitter?.value === 'cancel') return; e.preventDefault(); submit?.(new FormData(e.target)); }; }
function transactionModal(item = {}) { const type = item.type || 'expense', opts = t => data.categories[t].map(c=>`<option ${item.category===c?'selected':''}>${esc(c)}</option>`).join(''); openModal(item.id?'Редактировать операцию':'Новая операция', `<div class="type-switch"><label><input type="radio" name="type" value="expense" ${type==='expense'?'checked':''}> Расход</label><label><input type="radio" name="type" value="income" ${type==='income'?'checked':''}> Доход</label></div><label class="field">Сумма<input required name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" value="${item.amount ? item.amount/100 : ''}" autofocus></label><label class="field">Категория<select required name="category" id="modal-category">${opts(type)}</select></label><label class="field">Дата<input required name="date" type="date" value="${item.date||today()}"></label><label class="field">Способ оплаты<select name="payment">${['Карта','Наличные','Счёт','Другое'].map(x=>`<option ${item.payment===x?'selected':''}>${x}</option>`)}</select></label><label class="field">Комментарий <input name="note" value="${esc(item.note||'')}"></label><div class="modal-actions">${item.id?'<button class="danger ghost" type="button" data-action="delete-tx" data-id="'+item.id+'">Удалить</button>':''}<button class="primary">Сохранить</button></div>`, f => { const record = { id:item.id||uid(), type:f.get('type'), amount:toMinor(f.get('amount')), category:f.get('category'), date:f.get('date'), payment:f.get('payment'), note:f.get('note').trim() }; if (!record.amount || record.amount < 0) return toast('Введите корректную сумму'); const i=data.transactions.findIndex(x=>x.id===item.id); i<0?data.transactions.push(record):data.transactions[i]=record; $('#modal').close(); persist(); });
  $('#modal').querySelectorAll('input[name="type"]').forEach(r => r.onchange = e => $('#modal-category').innerHTML = opts(e.target.value));
}
function simpleModal(kind, item = {}) {
  const templates = { budget:['Лимит бюджета', `<label class="field">Категория<select name="category">${data.categories.expense.map(c=>`<option>${esc(c)}</option>`)}</select></label><label class="field">Лимит на месяц<input required name="limit" type="number" min="0.01" step="0.01" inputmode="decimal"></label>`, f=>data.budgets.push({id:uid(),category:f.get('category'),limit:toMinor(f.get('limit'))})], goal:['Новая цель', `<label class="field">Название<input required name="name" autofocus></label><label class="field">Желаемая сумма<input required name="target" type="number" min="0.01" step="0.01"></label><label class="field">Уже накоплено<input name="current" type="number" min="0" step="0.01" value="0"></label><label class="field">Срок (необязательно)<input name="deadline" type="date"></label>`, f=>data.goals.push({id:uid(),name:f.get('name').trim(),target:toMinor(f.get('target')),current:toMinor(f.get('current')),deadline:f.get('deadline'),color:'#136f63',icon:'◎'})], reminder:['Новое напоминание', `<label class="field">Название<input required name="name" autofocus></label><label class="field">Сумма (необязательно)<input name="amount" type="number" min="0" step="0.01"></label><label class="field">Дата<input required name="date" type="date" value="${today()}"></label><label class="field">Категория<select name="category">${data.categories.expense.map(c=>`<option>${esc(c)}</option>`)}</select></label>`, f=>data.reminders.push({id:uid(),name:f.get('name').trim(),amount:toMinor(f.get('amount')||0),date:f.get('date'),category:f.get('category'),paid:false})] };
  const [title, fields, add] = templates[kind]; openModal(title, fields+'<div class="modal-actions"><button class="primary">Сохранить</button></div>', f=>{add(f);$('#modal').close();persist();});
}
function toast(msg) { const el=$('#toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600); }
function filteredTransactions() { const type=$('#tx-type')?.value, cat=$('#tx-category')?.value; const rows=monthTransactions().filter(x=>(!type||x.type===type)&&(!cat||x.category===cat)).sort((a,b)=>b.date.localeCompare(a.date)); $('#all-transactions').innerHTML=rows.length?rows.map(txRow).join(''):empty('По этому фильтру операций нет.'); }

document.addEventListener('click', e => { const b=e.target.closest('[data-action],[data-go]'); if(!b) return; const a=b.dataset.action, id=b.dataset.id;
  if (b.dataset.go) { view=b.dataset.go; render(); return; }
  if(a==='add-tx') transactionModal(); else if(a==='edit-tx') transactionModal(data.transactions.find(x=>x.id===id)); else if(a==='delete-tx'){data.transactions=data.transactions.filter(x=>x.id!==id);$('#modal').close();persist();toast('Операция удалена');}
  else if(a==='add-budget') simpleModal('budget'); else if(a==='delete-budget'){data.budgets=data.budgets.filter(x=>x.id!==id);persist();} else if(a==='add-goal') simpleModal('goal'); else if(a==='delete-goal'){data.goals=data.goals.filter(x=>x.id!==id);persist();}
  else if(a==='fund-goal'){const g=data.goals.find(x=>x.id===id);openModal('Пополнить цель',`<p>${esc(g.name)}: ${money(g.current)} из ${money(g.target)}</p><label class="field">Сумма<input required type="number" name="amount" min="0.01" step="0.01" autofocus></label><div class="modal-actions"><button class="primary">Добавить</button></div>`,f=>{g.current+=toMinor(f.get('amount'));$('#modal').close();persist();});}
  else if(a==='add-reminder') simpleModal('reminder'); else if(a==='pay-reminder'){const r=data.reminders.find(x=>x.id===id);r.paid=true;if(r.amount && confirm(`Создать расход «${r.name}» на ${money(r.amount)}?`)) data.transactions.push({id:uid(),type:'expense',amount:r.amount,category:r.category,date:today(),payment:'Карта',note:r.name});persist();}
  else if(a==='add-category'){const name=prompt('Название категории'); if(name?.trim()&&!data.categories[b.dataset.type].includes(name.trim())){data.categories[b.dataset.type].push(name.trim());persist();}} else if(a==='remove-category'){data.categories[b.dataset.type].splice(+b.dataset.index,1);persist();}
  else if(a==='export-json') downloadJson(data); else if(a==='import-json') $('#import-file').click(); else if(a==='export-csv') downloadCsv(monthTransactions()); else if(a==='clear-data'&&confirm('Удалить все локально сохранённые данные? Это нельзя отменить.')) {localStorage.removeItem('my-finance-app-v1');data=loadData();persist();toast('Данные удалены');}
});
document.addEventListener('change', e=>{if(e.target.id==='tx-month'||e.target.id==='month-picker'){month=e.target.value;render();} if(e.target.id==='tx-type'||e.target.id==='tx-category')filteredTransactions(); if(e.target.id==='currency'){data.currency=e.target.value;persist();} if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);if(!Array.isArray(incoming.transactions))throw Error();data={...loadData(),...incoming,categories:{...loadData().categories,...incoming.categories}};persist();toast('Данные импортированы');}catch{toast('Не удалось прочитать этот файл.');}};reader.readAsText(file);e.target.value='';}});
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{view=b.dataset.page;render();});
$('#add-transaction').onclick=()=>transactionModal(); $('#theme-toggle').onclick=()=>{data.theme=data.theme==='dark'?'light':'dark';persist();};
render();
